### PR TITLE
Add aarch and ppc64le support and add traversaro as mantainer

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The library is just header-only, so there should not be any specific problem. I also add myself as maintainer as @seanyen is the only maintainer at the moment.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> The library is just header-only, so there should not be any specific problem. I also add myself as maintainer as @seanyen is the only maintainer at the moment.

The usual seven days period have passed, do you think we could merge this? @wolfv @conda-forge/core

**Comment by wolfv** [comment]
thanks for taking this over!

**Pull request merged**
